# Generated by Django 4.2.3 on 2023-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('depoimento', models.TextField(max_length=500)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
